version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - airflow_network

  airflow-webserver:
    image: apache/airflow:2.7.0
    container_name: airflow-webserver
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres:5432/admin
      AIRFLOW__WEBSERVER__SECRET_KEY: admin_secret_key
    volumes:
      - D:/testes/projeto_etl/infra/airflow/dags:/opt/airflow/dags
      - D:/testes/projeto_etl/infra/logs:/opt/airflow/logs
      - D:/testes/projeto_etl/infra/plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db upgrade && \
               airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com && \
               airflow webserver"
    networks:
      - airflow_network

  airflow-scheduler:
    image: apache/airflow:2.7.0
    container_name: airflow-scheduler
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres:5432/admin
    volumes:
      - D:/testes/projeto_etl/infra/airflow/dags:/opt/airflow/dags
      - D:/testes/projeto_etl/infra/logs:/opt/airflow/logs
      - D:/testes/projeto_etl/infra/plugins:/opt/airflow/plugins
    command: ["scheduler"]
    networks:
      - airflow_network

volumes:
  postgres_data:  # Definição correta do volume persistente

networks:
  airflow_network:
    driver: bridge
