version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - airflow_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - airflow_network

  airflow-webserver:
    image: apache/airflow:2.10.0
    container_name: airflow-webserver
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres:5432/admin
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://admin:admin@postgres:5432/admin
      AIRFLOW__WEBSERVER__SECRET_KEY: admin_secret_key
      PYTHONPATH: /opt/airflow
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../data:/opt/data/raw
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db upgrade && \
               airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com && \
               airflow webserver"
    networks:
      - airflow_network

  airflow-scheduler:
    image: apache/airflow:2.10.0
    container_name: airflow-scheduler
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres:5432/admin
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://admin:admin@postgres:5432/admin
      AIRFLOW__WEBSERVER__SECRET_KEY: admin_secret_key
      PYTHONPATH: /opt/airflow
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../data:/opt/data/raw
    command: >
      bash -c "airflow db upgrade && \
               airflow scheduler"
    networks:
      - airflow_network

  airflow-worker:
    image: apache/airflow:2.10.0
    container_name: airflow-worker
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres:5432/admin
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://admin:admin@postgres:5432/admin
      AIRFLOW__WEBSERVER__SECRET_KEY: admin_secret_key
      PYTHONPATH: /opt/airflow
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../data:/opt/data/raw
    command: airflow celery worker
    networks:
      - airflow_network

  airflow-flower:
    image: apache/airflow:2.10.0
    container_name: airflow-flower
    depends_on:
      - redis
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres:5432/admin
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://admin:admin@postgres:5432/admin
      AIRFLOW__WEBSERVER__SECRET_KEY: admin_secret_key
    command: airflow celery flower
    ports:
      - "5555:5555"
    networks:
      - airflow_network

volumes:
  postgres_data:

networks:
  airflow_network:
    driver: bridge